### ISSUE TITLE
Some turret types exist in-game but are not given a wiki page

### ISSUE THREAD

**Issue by pokedragonboy** [TrashMonks/qud-wiki#42]
Seemingly, there are several turret types which exist in-game as the product of a specific, corresponding turret tinker, but do not show up in ObjectBlueprints.xml, and thus do not have a corresponding page on the wiki. Specifically, these are:

- blast cannon turrets (from blast cannon tinkers)
- eigenturrets (from eigenturret tinkers)
- low light laser turrets (from low-light laser turret tinkers)

Dynamic turret tinkers throw another wrench into this, as they can create a turret from any ranged weapon, almost none of which have a corresponding wiki page, as they do not show up in ObjectBlueprints.xml.

**Comment by egocarib** [comment]
Fixed a few months ago
