### ISSUE TITLE
load individual creature water ritual skills

### ISSUE THREAD

**Issue by HeladoDeBrownie** [TrashMonks/qud-wiki#45]
we can use this for [this section](https://cavesofqud.gamepedia.com/Water_Ritual#Skills_That_Can_Be_Learned_Through_Water_Ritual) in order to provide a dynamically compiled comprehensive list of all water ritual skills, rather than just the faction ones

(special consideration is also due to neelahind, who gains the ritualable flag dynamically)

**Comment by Wreckstation** [comment]
i fixed this a while ago
