### ISSUE TITLE
QBE does not detect differences that are related to qudobject_wiki and not qudobject_props

### ISSUE THREAD

**Issue by Wreckstation** [TrashMonks/qud-wiki#57]
I have to manually edit some pages because `{{ID to page|Human Corpse}}` and `Human Corpse` are equivalent in QBE despite difference in formatting

**Comment by egocarib** [comment]
Seems to detect the difference for me (at least for this particular field/template I found, not sure if this is what you meant).
![image](https://user-images.githubusercontent.com/3429497/114482931-089c6400-9bcd-11eb-8927-949e937d7269.png)

**Comment by Wreckstation** [comment]
im fool i checked version diff against a template i already edited
