### ISSUE TITLE
inconsistent templates for plants and fungus

### ISSUE THREAD

**Issue by Wreckstation** [TrashMonks/qud-wiki#58]
some are characters and some are not. for example, lah blooms are items (?) although they certainly have combat abilities. to be fair the item/character dichotomy was not great in the first place but they should be more consistent. i propose that characters match what i put in ALL_CHARS (has physics, nontakeable, and also is not a gas).

**Comment by Wreckstation** [comment]
I did some initial tweaking to fix this but i haven't gotten around to mass uploading pages yet

**Comment by egocarib** [comment]
This was a great idea. I believe this is completely implemented now and all pages have been re-uploaded (with the plants described above now using the "Character" template.) I'm going to close the issue but feel free to re-open if you still intended to do something else.
