### ISSUE TITLE
Image upload for "Advertisment"

### ISSUE THREAD

**Issue by egocarib** [TrashMonks/qud-wiki#63]
For some reason, "MerchantAdvertisement" image seems to upload as a weird/empty image: https://wiki.cavesofqud.com/wiki/File:Advertisement_for_legendary_merchant.png

Not sure why this is, but crypto shows this tile fine, so I'm guessing it's something we're doing strange in the QBE upload process?

**Comment by syntaxaire** [comment]
This was being adblocked, which is very amusing to me.
Made an override to call this tile "scroll for legendary merchant" instead and uploaded.

**Comment by egocarib** [comment]
Seems to have re-surfaced; investigate whether override is still working / re-implement. LOL.

**Comment by Wreckstation** [comment]
For pages that use overrideimages for variations, the names are taken from self.tiles_and_metadata()'s filename, not image overrides from config. Not sure where this is defined and this is like a weird corner case that for now we can just manually rename. it probably won't be changing anytime soon

**Comment by egocarib** [comment]
I think this actually works from what I'm seeing. `self.tiles_and_metadata` ultimately pulls from `QudObject.image`. Since QBE uses the QudObject subclass `QudObjectWiki`, which has its own version of `def image` that pulls from the config, the alternate tiles use the config override too. In this example, I pulled your change to config which changes the name to "scroll..." and all the override images are based on that name too.

![image](https://user-images.githubusercontent.com/3429497/179327808-d2acec02-42e1-43f6-896e-750407f10e0e.png)
