### ISSUE TITLE
Wax Nodule Should Be an Item, Not a Character

### ISSUE THREAD

**Issue by egocarib** [TrashMonks/qud-wiki#69]
At some point QBE decided wax nodule was a character, but this seems incorrect.

https://wiki.cavesofqud.com/index.php?title=Wax_nodule&type=revision&diff=55729&oldid=53793

This causes some downstream issues, like wax nodule not showing its thrown weapon stats in its infobox or on this page:

https://wiki.cavesofqud.com/wiki/Thrown_weapon_combat#List_of_Thrown_Weapons

**Comment by librarianmage** [comment]
`Wax Nodule` has `Takeable="false"`, so is it still a projectile?

**Comment by egocarib** [comment]
Looks like that was indeed the cause of the issue, and it has since been updated in ObjectBlueprints to allow it to be takeable. It now renders using `Item` template and this issue can be closed.
